workflows:
  android-workflow:
    name: Open The Path Fixed Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.13.0
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Hard Clean Project
        script: |
          flutter clean
          rm -rf android/.gradle
          find . -name "*.apk" -type f -delete
      - name: Fetch Flutter Dependencies
        script: |
          flutter pub get
      - name: Execute Autonomous Android Release Build
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
