workflows:
  android-build:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.6 # هذا الإصدار المستقر يحل مشكلة الـ Kotlin تماماً في السيرفر
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - target: main
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/**/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true
